### ISSUE TITLE
Not transpiling to ES5

### ISSUE THREAD

**Issue by vaibhav93** [babel/babel-loader#214]
Here's my package.json deps
```js
"devDependencies": {
        "babel-core": "^6.5.2",
        "babel-preset-es2015": "^6.5.0",
        "babel-preset-stage-2": "^6.5.0",
        "babel-loader": "^6.2.2",
        "webpack": "^1.12.13"
    }
```
and webpack config
```js
module: {
            loaders: [
                {
                    test: /\.js?$/,
                    loader: 'babel',
                    exclude: /node_modules/,
                    query: {
                        presets: ['es2015']
                    }
                }
            ]
        }
```
The output file is not transpiled to es5.
npm v3.7.3
node v4.3.0

**Comment by Couto** [comment]
Can you show some example of the output code?

**Comment by vaibhav93** [comment]
https://gist.github.com/vaibhav93/6a68b7a0b341c54416b2

Here's the cmd output of running webpack
```
Hash: 33c6b192930e966770ab
Version: webpack 1.12.13
Time: 56ms
 Asset       Size            Chunks             Chunks name
bundle.js  1.53 kB       0  [emitted]        main
   [0] ./script.js 135 bytes {0} [built]
```

The compile es6 function should have looked like:
```js
"use strict";

var nameBuilder = function nameBuilder() {
    var firstName = arguments.length <= 0 || arguments[0] === undefined ? "John" : arguments[0];
    var lastName = arguments.length <= 1 || arguments[1] === undefined ? "Doe" : arguments[1];

    console.log(firstName + " " + lastName);
};
nameBuilder();

```

**Comment by Couto** [comment]
Does this also happens if you feed the babel binary directly?

**Comment by vaibhav93** [comment]
No. It works fine directly with
```js
babel --presets es2015 script.js --out-file bundled.js
```

**Comment by Couto** [comment]
Maybe I'm missing something, but i'm not able to replicate your issue.
I'm using the following example: https://gist.github.com/Couto/6c6164c24ae031bff935

**Comment by vaibhav93** [comment]
@Couto Thanks. Some silly mistake at my end. Had the module object in webpack config inside the output object.

**Comment by emretekince** [comment]
I have the same issue :(
my loader settings:
> {
                test: /\.js$/,
                // Skip any files outside of your project's `src` directory
                include: [
                    './public/js/src/'
                ],
                loader: "babel",
                query: {
                    presets: ['es2015']
                }
            }

**Comment by Couto** [comment]
@emretekince can you post your full config please?

**Comment by emretekince** [comment]
@Couto I have fixed it now by removing babel-loader from config file.
And now using inline command like :` require('babel!./script');`

**Comment by airtonix** [comment]
@emretekince @Couto  this doesn't really fix it, just avoids the problem.

**Comment by DavidShmu** [comment]
had the same issue here, was pulling my hair till I bump into this post.
babel --presets es2015 script.js --out-file bundled.js    --> did the trick

Thank you so much !
