### ISSUE TITLE
static defaultProps

### ISSUE THREAD

**Issue by oyb81076** [babel/babel-loader#347]
package.json
```
{
  "name": "h5",
  "version": "1.0.0",
  "description": "h5 single page to diy html pages",
  "main": "index.js",
  "scripts": {
    "dev": "webpack-dev-server --inline --content-base build/dev/ --port 8888",
    "hot": "webpack-dev-server --inline --hot",
    "test": "babel app/components/form/ColorInput.jsx",
		"build": "webpack"
  },
  "author": "ouyangbin",
  "readme": "README.md",
  "repository": {},
  "license": "MIT",
  "dependencies": {
    "bootstrap": "^3.3.7",
    "classnames": "^2.2.5",
    "font-awesome": "^4.7.0",
    "immutable": "^3.8.1",
    "jquery": "^3.1.1",
    "lodash": "^4.14.0",
    "moment": "^2.14.1",
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-immutable-proptypes": "^2.0.0",
    "redux": "^3.5.2",
    "redux-thunk": "^2.1.0",
    "reselect": "^2.5.3",
    "animate.css": "^3.5.2"
  },
  "devDependencies": {
    "add-asset-html-webpack-plugin": "^1.0.2",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.20.0",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.9",
    "babel-plugin-react-transform": "^2.0.2",
    "babel-plugin-transform-class-properties": "^6.19.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "babelify": "^7.3.0",
    "css-loader": "^0.26.0",
    "eslint": "^3.1.1",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-react": "^5.2.2",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "html-webpack-plugin": "^2.24.1",
    "node-sass": "^3.13.0",
    "react-hot-loader": "^1.3.1",
    "react-redux": "^4.4.5",
    "sass-loader": "^4.0.2",
    "style-loader": "^0.13.1",
    "svg-inline-loader": "^0.7.1",
    "svg-url-loader": "^1.1.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.14.0",
    "webpack-dev-server": "^1.16.2"
  }
}
```
webpack.config.js
```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
	entry: { app: './app/index.js' },
  output: {
		path: path.join(__dirname, '/build/runtime'),
		publicPath: '/',
		filename: '[name]/index.js'
	},
	devServer: {
		port: 8888,
		contentBase: './',
		inline: true
	},
	devtool: 'cheap-module-source-map',
	//devtool: "source-map",
	resolve:{
		root: './',
		extensions:['','.js','.json','.jsx'],
	},
	plugins: [
		new ExtractTextPlugin("[name]/index.css"),
		new HtmlWebpackPlugin({
			filename: 'app/index.html',
			template:'./app/index.html',
			inject:true,
			hash: false
		}),
	],
	module: {
		loaders: [
			{
				test: /\.jsx?$/,
				exclude: /(node_modules)/,
				loader: "babel-loader"
			},
			{ test: /\.js(x)?$/, exclude: /node_modules/, loaders: ['eslint-loader'] },
			{ test: /\.css$/, loader: ExtractTextPlugin.extract("css") },
			{ test: /\.sass$/, loader: ExtractTextPlugin.extract(["css-loader?sourceMap", "sass-loader?sourceMap"]) },
			{ test: /\.(ttf|eot|svg|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader?name=./fonts/[hash].[ext]" },
			{ test: /\.(png|jpg)$/, loader: 'url-loader?limit=1&name=image/[name]-[hash].[ext]'}
		]
	}
}
```
.babelrc
```
{
	"presets": [ "react", "es2015", "stage-0" ]
}
```

ColorInput.jsx
```
class ColorInput extends Component {
 static defaultProps = {
    autoPlay: false,
    maxLoops: 10,
  }
  constructor( props ) {
     super( props )
...
```
errors
```
ERROR in ./app/components/form/ColorInput.jsx

/Users/oyb/IdeaProjects/ganroft/h5/app/components/form/ColorInput.jsx
  8:22  error  Parsing error: Unexpected token =

✖ 1 problem (1 error, 0 warnings)
```
when run ` npm run test` to do `babel app/components/form/ColorInput.jsx`, works well

**Comment by danez** [comment]
This error looks like an eslint error and not like a webpack error.

Ensure you use babel-eslint to support class properties in eslint
https://github.com/babel/babel-eslint#setup

**Comment by oyb81076** [comment]
problem seems cause by eslint-loader
fixed by change
`{ test: /\.js(x)?$/, exclude: /node_modules/, loader: 'eslint-loader' },` to 
`{ test: /\.js(x)?$/, exclude: /node_modules/, loader: 'eslint?parser=babel-eslint' },`
[eslint-loader](https://github.com/MoOx/eslint-loader/issues/92)

**Comment by Manuelandro** [comment]
regardless @oyb81076 fix, i still have the problem

`{
		    	test: /\.js$/,
		    	exclude: /(node_modules|lib)/,
		    	loader: 'eslint?parser=babel-eslint',
				options: { fix: true }
		    }`

Everything works fine the Es-Lint Idle plugin, but when i run webpack i got it

`Module build failed: SyntaxError: Unexpected token (27:22)
  export const userAsync: { isAjaxStarted: boolean,`

**Comment by loganfsmyth** [comment]
@Manuelandro The best place for general support is StackOverflow. I'd recommend posting over there with your full Babel and Webpack configs and the error, and tagging it with `babeljs`.
