### ISSUE TITLE
parseQuery() will be replaced with getOptions() in the next major version of loader-utils

### ISSUE THREAD

**Issue by Regaddi** [babel/babel-loader#392]
**I'm submitting a feature request**

**Webpack Version:**
2.2.1

**Babel Core Version**:
6.5.2

**Babel Loader Version**:
6.3.2

**Please tell us about your environment:**
OSX 10.11.6

* **What is the motivation / use case for changing the behavior?**
See https://github.com/webpack/loader-utils/issues/56

**Comment by existentialism** [comment]
@Regaddi see https://github.com/babel/babel-loader/pull/391

**Comment by danez** [comment]
The deprecation warning is now fixed in v7.0.0-alpha.2

**Comment by damianobarbati** [comment]
@danez I still get the warning with: `"babel-loader": "v7.0.0-alpha.2"`

**Comment by danez** [comment]
Look at the stack-trace, the warning you are seeing is coming from the file-loader or url-loader.

Btw you can also use the final 7.0.0 version now.
